<form action="" method="POST">
	<fieldset>
		<legend>Authentification</legend>
		<table>
			<tr><td><label>E-mail </label></td><td><input type="text" name="mail" required /></td></tr>
			<tr><td><label>Mot de passe </label></td><td><input type="password" name="motDePasse" required/></td></tr>
			<tr>
				<td><input type="submit" value="connexion" name="connexion" /></td>
			</tr>
		</table>
		<?php if(isset($_GET['msg'])){echo 'MESSAGE: '.lireMessage();} ?>
</fieldset>
</form>